# Generated by Django 4.1.2 on 2022-10-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='published',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='title',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='email',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='password',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
